# Generated by Django 4.0.6 on 2022-07-11 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_albumelem_options_albumelem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumelem',
            name='bookmark',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
