# Generated by Django 4.0.6 on 2022-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_albumelem_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumelem',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
