# Generated by Django 4.0.6 on 2022-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_albumelem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumelem',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
