# Generated by Django 4.0.6 on 2022-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumElem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('content', models.TextField(blank=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
