# Generated by Django 4.0.6 on 2022-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumelem',
            options={'verbose_name': 'Статьи на сайте', 'verbose_name_plural': 'Статьи на сайте'},
        ),
        migrations.AddField(
            model_name='albumelem',
            name='title',
            field=models.TextField(default='Название города', max_length=255),
        ),
    ]
